[package]
name = "gdal-sys"
description = "Low level GDAL bindings for Rust"
license = "MIT"
version = "3.3.0"
repository = "https://github.com/georust/gdal"
authors = ["Johannes Drönner <droenner@informatik.uni-marburg.de>"]
edition = "2018"

[features]
default = ["min_gdal_version_1_11"]
min_gdal_version_1_11 = []
min_gdal_version_2_0 = []
min_gdal_version_2_1 = []
min_gdal_version_2_2 = []
min_gdal_version_2_3 = []
min_gdal_version_2_4 = []
min_gdal_version_3_0 = []
min_gdal_version_3_2 = []

[dependencies]
libc = "0.2"

[build-dependencies]
bindgen = { version = "0.55.1", optional = true }
pkg-config = "0.3"
