language: rust

dist: xenial

rust:
  - stable
  - beta
  - nightly

before_install:
  - sudo apt-get update
  - sudo apt-get install libgeos-dev python3

script:
  - cargo build
  - cargo build --features v3_6_0
  - cargo build --features v3_7_0
  - cargo build --features v3_8_0
  # to check that the bindings match the C definitions
  - python3 check_missing/check_missing.py
